### PR TITLE
Fix inaccurate vehicle status info

### LINKED ISSUE #499: Last Comms and Next surface schedule inaccurate when viewing Vehicle Status Info.
**Describe the bug**
Quinn S. - Status info comms indicator is displaying the wrong information. 
Example, pontus is deployed and had a last comms only moments ago and
is scheduled to surface in 25 minutes (30 minutes after transit start). However,
the Status info for the deployed vehicle is displaying the wrong information
(see image attached) - certainly not the current deployment schedule.

**To Reproduce**
1. Set schedule of vehicle (know set schedule times)
2. Begin transit schedule.
3. Monitor vehicle's last cell com and estimated time to surface based on schedule.
4. Hover over Vehicle Status popup and check accuracy. 

**Expected behavior**
When the vehicle status popup is shown it should be accurate with the schedule
of the vehicle's current deployment. 

**Screenshots**
Link:  https://files.slack.com/files-pri/T0652RU62GN-F09NKDC6UCX/screenshot_from_2025-10-27_15-39-41.png

Image: 

Image

### PR DESCRIPTION
**Pull request by ZackLyon**
Fix the inaccurate vehicle status info for comms and current vehicle state in the pop-ups below the user avatar on the deployment page

## Communication Status Improvements
- **Implemented next comms time display on deployment page** - Shows when the next communication is expected for both satellite and cell communications
- **Created `useNeedCommsTime` hook** - Provides need comms time information based on mission data and events
- **Updated `useLastCommsTime` hook** - Now provides last comms information for both satellite and cell communications separately
- **Updated VehicleInfoCell component** - Displays information about both satellite and cell communications with separate status indicators
- **Refactored VehicleInfoCell** - Added PluggedIn state to better track vehicle connection status
- **Created helper functions for calculating next comms time** (`calculateNextComm`) - Utilities for computing when next communication is needed based on mission defaults and event data (only parse mission data up to one minute before mission start)
- **Created helper functions for formatting next comms times** (`nextCommsTimeFormatting`) - Formatting utilities for displaying comms time information in a user-friendly format
- **Created helper function for displaying relative duration** (`formatCompactDuration`) - Shows time in shortened days, hours, minutes format (e.g., "2d 3h 15m")
- **Created helper functions to parse need comms related data from events** (`parseNeedComms`) - Utilities for extracting comms information from event data, including parsing mission commands and event notes
- **Default need comms times for standard missions** (`needCommsMissionDefaults`) - Added default values for standard mission types to use when mission-specific data is not available

## UI/UX Improvements
- **Created `useTick` hook** - Helper function to update UI on a certain interval without unnecessary rerenders, used for updating relative time displays
- **Updated `useCurrentDeployment`** - Now returns last deployment so launch and recovery events are available, which are needed for accurate status calculations
- **Fix html in Mission text** - The mission text now displays a dot separator instead of `&#x2022;` in the vehicle diagram
- **Enforce y-axis scroll for vehicle list** - On overview page, always show scroll bar in the vehicle list to avoid virtualized list sometimes falling into an infinite loop of resizing
- **Vehicle diagrams work in local development** - Provide fallback url for getting vehicle diagram info while in local development

## Code Refactoring & Architecture Improvements

- **Refactored `useVehicleInfo` hook** - Centralized fallback logic for vehicle info API calls within the hook itself, eliminating duplicate fallback code in `VehicleList` and `VehicleDiagram` components

- **Updated `useVehicleInfo` with fallback strategy** - Hook now automatically falls back to siteConfig URL pattern when primary API endpoint fails or returns not_found, improving reliability and reducing code duplication

- **Implemented updated useVehicleInfo to replace separate fallback strategies** - Removed redundant fallback implementations from `VehicleList.tsx` and `VehicleDiagram.tsx`, simplifying component code and ensuring consistent fallback behavior across all vehicle info usage

Closes #499

### Next Comms
Screenshot 2025-11-10 at 4 37 27 PM

### Last Comms
Screenshot 2025-11-10 at 4 37 04 PM

### Corresponding AUV Diagram (note: diagram does not update as often so it's relative time - ie "in 9m" - is often off by a couple minutes)
Screenshot 2025-11-10 at 4 38 22 PM

### CODE REVIEW

File: apps/lrauv-dash2/components/VehicleDiagram.tsx [hunk 1]
```diff
@@ -92,9 +179,19 @@ const VehicleDiagram: React.FC<{
...
         colorCartCircle={vehicle?.color_cartcircle}
         colorThrust={vehicle?.color_thrust}
-        textSat={vehicle?.text_sat}
+        textSat={formattedSatTime}
         textLogTime={vehicle?.text_logtime}
-        textMission={vehicle?.text_mission ?? ''}
+        textMission={
+          vehicle?.text_mission
+            ? vehicle.text_mission
+                .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) =>
```
Comment (jimjeffers) [inline apps/lrauv-dash2/components/VehicleDiagram.tsx]: It looks like you've got this inline method defined in multiple places. Would be better off as a method refactored into our mbari/utils package incase we find an issue with this later but only notice it in one of the two use cases.

File: apps/lrauv-dash2/components/VehicleList.tsx [hunk 2]
```diff
@@ -176,100 +374,30 @@ const ConnectedVehicleCell: React.FC<{
...
+// No memoization - let it update when data changes
+const ConnectedVehicleCell = ConnectedVehicleCellComponent
+
 const VehicleList: React.FC<{
   onSelectVehicle?: (vehicle: string) => void
 }> = ({ onSelectVehicle: handleSelectVehicle }) => {
   const { trackedVehicles } = useTrackedVehicles()
   const { data: siteConfig } = useSiteConfig()
 
+  console.log('zzz siteConfig', siteConfig)
```
Comment (jimjeffers) [inline apps/lrauv-dash2/components/VehicleList.tsx]: Safe to remove this debug log before merge?

**Review by jimjeffers — COMMENTED** [review]
@ZackLyon some minor nitpicks but otherwise looks really good. The only big ask -- are you essentially doing the same thing in the `VehicleDiagram` and `VehicleList`? If so should we keep it dry and make a `useVehicleInfoWithFallback` to handle this cleanly in both?

**Comment by ZackLyon** [comment]
@jimjeffers - I implemented the changes you requested, then merged
